/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel/index'
import { Route as AuthenticatedPainelCatalogoRouteImport } from './routes/_authenticated/painel/catalogo'
import { Route as AuthenticatedPainelCerebroRouteImport } from './routes/_authenticated/painel/cerebro'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel/configuracoes'
import { Route as AuthenticatedPainelConsumoIaRouteImport } from './routes/_authenticated/painel/consumo-ia'
import { Route as AuthenticatedPainelDocumentacaoRouteImport } from './routes/_authenticated/painel/documentacao'
import { Route as AuthenticatedPainelHandoffsRouteImport } from './routes/_authenticated/painel/handoffs'
import { Route as AuthenticatedPainelIntegracoesRouteImport } from './routes/_authenticated/painel/integracoes'
import { Route as AuthenticatedPainelLaboratorioRouteImport } from './routes/_authenticated/painel/laboratorio'
import { Route as AuthenticatedPainelLeadsRouteImport } from './routes/_authenticated/painel/leads'
import { Route as AuthenticatedPainelLogsRouteImport } from './routes/_authenticated/painel/logs'
import { Route as AuthenticatedPainelLojasRouteImport } from './routes/_authenticated/painel/lojas'
import { Route as AuthenticatedPainelUsuariosRouteImport } from './routes/_authenticated/painel/usuarios'
import { Route as ApiPublicAgenteKommoRouteImport } from './routes/api/public/agente/kommo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelCatalogoRoute =
  AuthenticatedPainelCatalogoRouteImport.update({
    id: '/painel/catalogo',
    path: '/painel/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelCerebroRoute =
  AuthenticatedPainelCerebroRouteImport.update({
    id: '/painel/cerebro',
    path: '/painel/cerebro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/painel/configuracoes',
    path: '/painel/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelConsumoIaRoute =
  AuthenticatedPainelConsumoIaRouteImport.update({
    id: '/painel/consumo-ia',
    path: '/painel/consumo-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelDocumentacaoRoute =
  AuthenticatedPainelDocumentacaoRouteImport.update({
    id: '/painel/documentacao',
    path: '/painel/documentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelHandoffsRoute =
  AuthenticatedPainelHandoffsRouteImport.update({
    id: '/painel/handoffs',
    path: '/painel/handoffs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIntegracoesRoute =
  AuthenticatedPainelIntegracoesRouteImport.update({
    id: '/painel/integracoes',
    path: '/painel/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelLaboratorioRoute =
  AuthenticatedPainelLaboratorioRouteImport.update({
    id: '/painel/laboratorio',
    path: '/painel/laboratorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelLeadsRoute =
  AuthenticatedPainelLeadsRouteImport.update({
    id: '/painel/leads',
    path: '/painel/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelLogsRoute = AuthenticatedPainelLogsRouteImport.update({
  id: '/painel/logs',
  path: '/painel/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelLojasRoute =
  AuthenticatedPainelLojasRouteImport.update({
    id: '/painel/lojas',
    path: '/painel/lojas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelUsuariosRoute =
  AuthenticatedPainelUsuariosRouteImport.update({
    id: '/painel/usuarios',
    path: '/painel/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgenteKommoRoute = ApiPublicAgenteKommoRouteImport.update({
  id: '/api/public/agente/kommo',
  path: '/api/public/agente/kommo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel/catalogo': typeof AuthenticatedPainelCatalogoRoute
  '/painel/cerebro': typeof AuthenticatedPainelCerebroRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/consumo-ia': typeof AuthenticatedPainelConsumoIaRoute
  '/painel/documentacao': typeof AuthenticatedPainelDocumentacaoRoute
  '/painel/handoffs': typeof AuthenticatedPainelHandoffsRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/laboratorio': typeof AuthenticatedPainelLaboratorioRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/logs': typeof AuthenticatedPainelLogsRoute
  '/painel/lojas': typeof AuthenticatedPainelLojasRoute
  '/painel/usuarios': typeof AuthenticatedPainelUsuariosRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/agente/kommo': typeof ApiPublicAgenteKommoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel/catalogo': typeof AuthenticatedPainelCatalogoRoute
  '/painel/cerebro': typeof AuthenticatedPainelCerebroRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/consumo-ia': typeof AuthenticatedPainelConsumoIaRoute
  '/painel/documentacao': typeof AuthenticatedPainelDocumentacaoRoute
  '/painel/handoffs': typeof AuthenticatedPainelHandoffsRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/laboratorio': typeof AuthenticatedPainelLaboratorioRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/logs': typeof AuthenticatedPainelLogsRoute
  '/painel/lojas': typeof AuthenticatedPainelLojasRoute
  '/painel/usuarios': typeof AuthenticatedPainelUsuariosRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/agente/kommo': typeof ApiPublicAgenteKommoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel/catalogo': typeof AuthenticatedPainelCatalogoRoute
  '/_authenticated/painel/cerebro': typeof AuthenticatedPainelCerebroRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/consumo-ia': typeof AuthenticatedPainelConsumoIaRoute
  '/_authenticated/painel/documentacao': typeof AuthenticatedPainelDocumentacaoRoute
  '/_authenticated/painel/handoffs': typeof AuthenticatedPainelHandoffsRoute
  '/_authenticated/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/_authenticated/painel/laboratorio': typeof AuthenticatedPainelLaboratorioRoute
  '/_authenticated/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/_authenticated/painel/logs': typeof AuthenticatedPainelLogsRoute
  '/_authenticated/painel/lojas': typeof AuthenticatedPainelLojasRoute
  '/_authenticated/painel/usuarios': typeof AuthenticatedPainelUsuariosRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/agente/kommo': typeof ApiPublicAgenteKommoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel/catalogo'
    | '/painel/cerebro'
    | '/painel/configuracoes'
    | '/painel/consumo-ia'
    | '/painel/documentacao'
    | '/painel/handoffs'
    | '/painel/integracoes'
    | '/painel/laboratorio'
    | '/painel/leads'
    | '/painel/logs'
    | '/painel/lojas'
    | '/painel/usuarios'
    | '/painel/'
    | '/api/public/agente/kommo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel/catalogo'
    | '/painel/cerebro'
    | '/painel/configuracoes'
    | '/painel/consumo-ia'
    | '/painel/documentacao'
    | '/painel/handoffs'
    | '/painel/integracoes'
    | '/painel/laboratorio'
    | '/painel/leads'
    | '/painel/logs'
    | '/painel/lojas'
    | '/painel/usuarios'
    | '/painel'
    | '/api/public/agente/kommo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel/catalogo'
    | '/_authenticated/painel/cerebro'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/consumo-ia'
    | '/_authenticated/painel/documentacao'
    | '/_authenticated/painel/handoffs'
    | '/_authenticated/painel/integracoes'
    | '/_authenticated/painel/laboratorio'
    | '/_authenticated/painel/leads'
    | '/_authenticated/painel/logs'
    | '/_authenticated/painel/lojas'
    | '/_authenticated/painel/usuarios'
    | '/_authenticated/painel/'
    | '/api/public/agente/kommo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgenteKommoRoute: typeof ApiPublicAgenteKommoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/catalogo': {
      id: '/_authenticated/painel/catalogo'
      path: '/painel/catalogo'
      fullPath: '/painel/catalogo'
      preLoaderRoute: typeof AuthenticatedPainelCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/cerebro': {
      id: '/_authenticated/painel/cerebro'
      path: '/painel/cerebro'
      fullPath: '/painel/cerebro'
      preLoaderRoute: typeof AuthenticatedPainelCerebroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/painel/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/consumo-ia': {
      id: '/_authenticated/painel/consumo-ia'
      path: '/painel/consumo-ia'
      fullPath: '/painel/consumo-ia'
      preLoaderRoute: typeof AuthenticatedPainelConsumoIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/documentacao': {
      id: '/_authenticated/painel/documentacao'
      path: '/painel/documentacao'
      fullPath: '/painel/documentacao'
      preLoaderRoute: typeof AuthenticatedPainelDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/handoffs': {
      id: '/_authenticated/painel/handoffs'
      path: '/painel/handoffs'
      fullPath: '/painel/handoffs'
      preLoaderRoute: typeof AuthenticatedPainelHandoffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/integracoes': {
      id: '/_authenticated/painel/integracoes'
      path: '/painel/integracoes'
      fullPath: '/painel/integracoes'
      preLoaderRoute: typeof AuthenticatedPainelIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/laboratorio': {
      id: '/_authenticated/painel/laboratorio'
      path: '/painel/laboratorio'
      fullPath: '/painel/laboratorio'
      preLoaderRoute: typeof AuthenticatedPainelLaboratorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/leads': {
      id: '/_authenticated/painel/leads'
      path: '/painel/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof AuthenticatedPainelLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/logs': {
      id: '/_authenticated/painel/logs'
      path: '/painel/logs'
      fullPath: '/painel/logs'
      preLoaderRoute: typeof AuthenticatedPainelLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/lojas': {
      id: '/_authenticated/painel/lojas'
      path: '/painel/lojas'
      fullPath: '/painel/lojas'
      preLoaderRoute: typeof AuthenticatedPainelLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/usuarios': {
      id: '/_authenticated/painel/usuarios'
      path: '/painel/usuarios'
      fullPath: '/painel/usuarios'
      preLoaderRoute: typeof AuthenticatedPainelUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agente/kommo': {
      id: '/api/public/agente/kommo'
      path: '/api/public/agente/kommo'
      fullPath: '/api/public/agente/kommo'
      preLoaderRoute: typeof ApiPublicAgenteKommoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelCatalogoRoute: typeof AuthenticatedPainelCatalogoRoute
  AuthenticatedPainelCerebroRoute: typeof AuthenticatedPainelCerebroRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelConsumoIaRoute: typeof AuthenticatedPainelConsumoIaRoute
  AuthenticatedPainelDocumentacaoRoute: typeof AuthenticatedPainelDocumentacaoRoute
  AuthenticatedPainelHandoffsRoute: typeof AuthenticatedPainelHandoffsRoute
  AuthenticatedPainelIntegracoesRoute: typeof AuthenticatedPainelIntegracoesRoute
  AuthenticatedPainelLaboratorioRoute: typeof AuthenticatedPainelLaboratorioRoute
  AuthenticatedPainelLeadsRoute: typeof AuthenticatedPainelLeadsRoute
  AuthenticatedPainelLogsRoute: typeof AuthenticatedPainelLogsRoute
  AuthenticatedPainelLojasRoute: typeof AuthenticatedPainelLojasRoute
  AuthenticatedPainelUsuariosRoute: typeof AuthenticatedPainelUsuariosRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelCatalogoRoute: AuthenticatedPainelCatalogoRoute,
  AuthenticatedPainelCerebroRoute: AuthenticatedPainelCerebroRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelConsumoIaRoute: AuthenticatedPainelConsumoIaRoute,
  AuthenticatedPainelDocumentacaoRoute: AuthenticatedPainelDocumentacaoRoute,
  AuthenticatedPainelHandoffsRoute: AuthenticatedPainelHandoffsRoute,
  AuthenticatedPainelIntegracoesRoute: AuthenticatedPainelIntegracoesRoute,
  AuthenticatedPainelLaboratorioRoute: AuthenticatedPainelLaboratorioRoute,
  AuthenticatedPainelLeadsRoute: AuthenticatedPainelLeadsRoute,
  AuthenticatedPainelLogsRoute: AuthenticatedPainelLogsRoute,
  AuthenticatedPainelLojasRoute: AuthenticatedPainelLojasRoute,
  AuthenticatedPainelUsuariosRoute: AuthenticatedPainelUsuariosRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgenteKommoRoute: ApiPublicAgenteKommoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}